# Generated by Django 3.2.13 on 2022-06-04 19:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollster', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pollster.question'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('question', 'user')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
    ]
