# Generated by Django 3.2.13 on 2022-06-04 23:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollster', '0004_vote_choice'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('choice', 'user')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
    ]
